spring.application.name=FintechBackend

spring.data.mongodb.uri=mongodb+srv://alish_db_user:Tolegen228@cluster0.q7hw2qj.mongodb.net/fintechdb?retryWrites=true&w=majority&appName=Cluster0

server.port=8080

# ?????? ? ??????????? ?????? ?? ??????? ????????? ?????? ? ?? ??????? ? git
jwt.secret=dlinaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_a
# ????? ????? ?????? ? ????????????? (?? ????????? 1 ???)
jwt.expirationMs=3600000

supabase:
supabase.url: https://apiznugqnoybttaifzsi.supabase.co
supabase.key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwaXpudWdxbm95YnR0YWlmenNpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE3Nzk4NSwiZXhwIjoyMDg3NzUzOTg1fQ.2PNz6lj3vHstQn5pPbKVDWmcBpC1xVyYvjmTTUqphps
supabase.bucket: avatars

# application.properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alishertolegen1337@gmail.com
spring.mail.password=tipi pkfe yxpx dknc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-url=http://localhost:5173