spring.application.name=FintechBackend

spring.data.mongodb.uri=mongodb+srv://admin:TTT1337@fintech.siwtwbp.mongodb.net/Fintech?retryWrites=true&w=majority

server.port=8080

# ?????? ? ??????????? ?????? ?? ??????? ????????? ?????? ? ?? ??????? ? git
jwt.secret=dlinaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_a
# ????? ????? ?????? ? ????????????? (?? ????????? 1 ???)
jwt.expirationMs=3600000

supabase:
supabase.url: https://apiznugqnoybttaifzsi.supabase.co
supabase.key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwaXpudWdxbm95YnR0YWlmenNpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE3Nzk4NSwiZXhwIjoyMDg3NzUzOTg1fQ.2PNz6lj3vHstQn5pPbKVDWmcBpC1xVyYvjmTTUqphps
supabase.bucket: avatars